# open.sub
# starter submit file for CHTC jobs

universe = docker
docker_image = zhuoyanxu/single_cell:update

log = log/open_job_$(Cluster).log
error = OutputError/job_$(Cluster)_$(Process).err
output = OutputError/job_$(Cluster)_$(Process).out

executable = runPy.sh
arguments = $(ProcID)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = /home/zxu444/open/func/prepro.py, k_centers_targets.csv.gz, /home/zxu444/open/models/model_predict.py, linearTorch.py

# IMPORTANT! Require execute servers that can access /staging
Requirements = (Target.HasCHTCStaging == true)

request_cpus = 1
request_memory = 100GB
request_disk = 50GB

queue 1