# Software build file

universe = docker
docker_image = zhuoyanxu/single_cell:update
log = interactive.log

# change the name of the file to be the name of your source code

# should_transfer_files = YES
# when_to_transfer_output = ON_EXIT
# transfer_input_files = /home/zxu444/open_problem/GPU/open/func/prepro.py, /home/zxu444/open_problem/GPU/open/models/model_predict.py


+IsBuildJob = true
# requirements = (OpSysMajorVer =?= 8)
# request_cpus = 1
# request_memory = 4GB
# request_disk = 2GB

# IMPORTANT! Require execute servers that can access /staging
Requirements = (Target.HasCHTCStaging == true && Target.CUDAGlobalMemoryMb > 4000)

request_cpus = 1
request_memory = 16GB
request_disk = 20GB
request_gpus = 1
+GPUJobLength = "short"
+WantGPULab = true
+wantFlocking = true

queue