# template.sub
# starter submit file for CHTC jobs

universe = docker
docker_image = zhuoyanxu/single_cell:update

log = job_$(Cluster).log
error = job_$(Cluster)_$(Process).err
output = job_$(Cluster)_$(Process).out

executable = runPy.sh
arguments = $(ProcID)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = testPy.py train_multi_inputs.h5 train_multi_targets.h5 test_multi_inputs.h5

request_cpus = 1
request_memory = 100GB
request_disk = 1GB

queue 1