# template.sub
# starter submit file for CHTC jobs

universe = docker
docker_image = zhuoyanxu/single_cell:update

log = job_$(Cluster).log
error = job_$(Cluster)_$(Process).err
output = job_$(Cluster)_$(Process).out

executable = runPy.sh
arguments = $(ProcID)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = testStaging.py

# IMPORTANT! Require execute servers that can access /staging
Requirements = (Target.HasCHTCStaging == true)

request_cpus = 1
request_memory = 15GB
request_disk = 15GB

queue 1